services:
  server:
    build: ./server
    container_name: collatz-server
    environment:
      THREAD_COUNT: "8"
    ports:
      - "9000:9000"
    networks:
      - collatz-net

  client:
    build: ./client
    container_name: collatz-client
    depends_on:
      - server
    environment:
      SERVER_HOST: server
      SERVER_PORT: "9000"
      COLLATZ_COUNT: "10"
    networks:
      - collatz-net

networks:
  collatz-net:
    driver: bridge